source = $HOME/.config/hypr/hyprlock.d/macchiato.conf

$accent = $mauve
$accentAlpha = $mauveAlpha
$font = JetBrains Mono

# GENERAL
general {
  hide_cursor = true
}

# AUTHENTICATION
auth {
  pam:enabled = true
  fingerprint:enabled = true
}

# BACKGROUND
background {
  monitor =
  path = $HOME/.wallpapers/japan-blurred.png
  blur_passes = 0
  color = $base
}

# TIME
label {
  monitor =
  text = $TIME
  color = $text
  font_size = 90
  font_family = $font
  position = 0, 240
  halign = center
  valign = center
}

# DATE
label {
  monitor =
  text = cmd[update:60000] date +"%A, %d %B %Y"
  color = $subtext1
  font_size = 25
  font_family = $font
  position = 0, 110
  halign = center
  valign = center
}

# GREETING
label {
  monitor =
  text = cmd[update:60000] bash -c 'h=$(date +%H); if [ $h -lt 12 ]; then echo "good morning, ta!"; elif [ $h -lt 18 ]; then echo "good afternoon, ta!"; else echo "good evening, ta!"; fi'
  color = $subtext1
  font_size = 26
  font_family = $font
  position = 0, 20
  halign = center
  valign = center
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $surface0
  font_color = $text
  font_family = $font
  fade_on_empty = false
  placeholder_text = <span foreground="##$accentAlpha">$USER</span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -75
  halign = center
  valign = center
}

# FINGERPRINT PROMPT
label {
  monitor =
  text = $FPRINTPROMPT
  color = $subtext0
  font_size = 14
  font_family = $font
  position = 0, -150
  halign = center
  valign = center
}
