general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

# turn off keyboard backlight after 1 minute 
listener { 
    timeout = 60
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

# dim screen after 5 minutes
listener {
    timeout = 300
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# lock screen after 10 minutes
listener {
    timeout = 600
    on-timeout = loginctl lock-session
    on-resume = notify-send "Welcome back!"
}

# turn off screen after 15 minutes
listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

# shutdown after 1 hour
listener {
    timeout = 3600
    on-timeout = idle-shutdown
}

