max = 100
timeout = 2000
width = 16
height = 200
border_size = 1
border_offset = 1
bar_padding = 1
anchor = left
margin = 0 0 0 20
orientation = vertical

# Catppuccin Macchiato
border_color = 8aadf4FF
background_color = 24273aFF
bar_color = f5a97fFF
