# Hyprland config file
# Refer to the wiki for more information.
# https://wiki.hyprland.org/Configuring/

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf


################
### MONITORS ###
################

# @see https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,auto


###################
### MY PROGRAMS ###
###################

# @see https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = ghostty
$menu = wofi --show drun


#############################
### ENVIRONMENT VARIABLES ###
#############################

# @see https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


#################
### AUTOSTART ###
#################
source = ~/.config/hypr/autostarts.conf


#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hyprland.org/Configuring/Variables/

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false
    layout = master
}

# @see https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = slave
    new_on_top = true
}

# visual effects: decorations, animations
source = ~/.config/hypr/visualeffects.conf


#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    follow_mouse = 2
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    kb_options = ctrl:nocaps # remap capslock to ctrl

    touchpad {
    	disable_while_typing = true
        natural_scroll = false
	drag_lock = true
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe = true
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}


###################
### KEYBINDINGS ###
###################
source = ~/.config/hypr/keybinds.conf


##############################
### WINDOWS AND WORKSPACES ###
##############################

# @see https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# @see https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
windowrule = rounding 0, floating:0, onworkspace:w[tv1]
windowrule = bordersize 0, floating:0, onworkspace:f[1]
windowrule = rounding 0, floating:0, onworkspace:f[1]


##############################
###    MISC AND DEBUG      ###
##############################
# @see https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0 # set to 0 or 1 to disable the mascot wallpapers
    disable_hyprland_logo = true # disables the random hyprland wallpapers
}

debug {
    disable_logs = false
    disable_time = false
    enable_stdout_logs = true
}

